### ISSUE TITLE
bug: feature "hash" not no_std compatible

### ISSUE THREAD

**Issue by tdelabro** [starknet-io/types-rs#29]
Adding the feature "hash" to dependency `starknet-types-core` in `ensure_no_std/Cargo.tom` results in a failure to build.
This is weird because the code behind the "hash" feature flag doesn't import anything from "std" and the only dep it add to the equation is labdaclass-crypto, wich is supposed to be no-std

**Comment by tdelabro** [comment]
@pefontana @Oppen do you know something about that? You want to work on it yourselves or should I put someone onto it?

**Comment by Oppen** [comment]
I think the culprit is an oversight in `lambdaworks-crypto` deps:
```toml
[dependencies]
lambdaworks-math.workspace = true
sha3 = "0.10"
sha2 = "0.10"
thiserror = "1.0.38"
serde = { version = "1.0", features = ["derive"] }
rayon = { version = "1.8.0", optional = true }
```
None of them is disabling the default features, so `thiserror` and `serde`, at least, are assuming `std` IIUC. This should be fixed in `lambdaworks`.
